app:
  forecast_features_path: data/processed/forecast_features.parquet
  gru_model_path: artefacts/gru4rec.pt
  host: 0.0.0.0
  item2idx_path: artefacts/item2idx.json
  lightgbm_model_path: artefacts/lightgbm_weighted.pkl
  max_seq_length: 50
  port: 8000
  reco_sequences_path: data/processed/reco_sequences.parquet
clean:
  bot_threshold_per_day: 10000
  dedupe: true
  drop_missing_category: true
  out_dir: data/interim
  raw_dir: data/raw
features:
  forecast_horizon_days: 7
  freq: D
  in_dir: data/interim
  item2idx_path: artefacts/item2idx.json
  max_seq_length: 50
  min_interactions_per_user: 5
  out_dir: data/processed
  processed_forecast_path: forecast_features.parquet
  processed_reco_path: reco_sequences.parquet
  rolling_window_days: 30
models:
  artefacts_dir: artefacts
  features_dir: data/processed
  forecast:
    bagging_fraction: 0.8224507808606525
    bagging_freq: 10
    bf: 0.4080675456901738
    bfreq: 13
    drop_zero_target: true
    early_stopping_rounds: 30
    feature_fraction: 0.8227344112609893
    ff: 0.3621803088338233
    l1: 0.0004189119968024943
    l2: 0.007146279195994392
    lambda_l1: 0.4570098424675586
    lambda_l2: 7.6773815425519825
    leaf_min: 5
    learning_rate: 0.28998330671106737
    leaves: 20
    lr: 0.07482753672810354
    metric: mae
    min_data_in_leaf: 7
    num_boost_round: 300
    num_leaves: 20
    objective: regression
    optuna_db_path: artefacts/optuna_forecast.db
    optuna_pruner: median
    optuna_timeout_minutes: 20
    optuna_trials: 25
    tuned_model_weighted_path: artefacts/lightgbm_tuned_weighted.pkl
    tvp: 1.8432648495618793
    tweedie_variance_power: 1.8432648495618793
    use_sample_weight: true
    weighted_model_path: artefacts/lightgbm_weighted.pkl
  optuna_trials: 25
  reco:
    batch_size: 128
    embedding_dim: 32
    epochs: 5
    hidden_size: 64
    learning_rate: 0.001
    tuned_metrics_path: reports/metrics_reco_tuned.yaml
    tuned_model_path: artefacts/gru4rec.pt
  val_split_days: 7
report:
  notebook_path: notebooks/99_report.ipynb
  pdf_path: reports/report.pdf
